// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CenterNodeRpcServer.proto

package com.tangjian.grpc.rpc.service;

public final class CenterNodeServer {
  private CenterNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031CenterNodeRpcServer.proto\022\025com.tangjia" +
      "n.grpc.rpc\032\030CenterNodeRpcModel.proto2\320\001\n" +
      "\021CenterNodeService\022[\n\010register\022&.com.tan" +
      "gjian.grpc.rpc.RegisterRequest\032\'.com.tan" +
      "gjian.grpc.rpc.RegisterResponse\022^\n\theart" +
      "beat\022\'.com.tangjian.grpc.rpc.HeartbeatRe" +
      "quest\032(.com.tangjian.grpc.rpc.HeartbeatR" +
      "esponseB3\n\035com.tangjian.grpc.rpc.service" +
      "B\020CenterNodeServerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tangjian.grpc.rpc.model.CenterNodeRpcModel.getDescriptor(),
        });
    com.tangjian.grpc.rpc.model.CenterNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
